function [ leaf ] = createLeafV2(value, id)
% creates a kd-tree leaf 
% value - (real) the value of the leaf

%     leaf = struct('dimNumber', 0,...
%                   'dimValue', value,...
%                   'left', 0,...
%                   'right', 0,...
%                   'isLeaf', true);

    leaf = struct('point', value, ...
                  'ID', id,...
                  'isLeaf', true);


end

